
public class Main {

	public static void main(String[] args) {
		// Even Fibonacci numbers
		// //////////////////////
		
		/*
		 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
		 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
		 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
		 */
		
		// # of attempts:	1
		// success:			true
		
		
		int fib_0 = 0;
		int fib_1 = 1;	// init
		int fib_2 = 0;
		
		int sumEvenFib = 0;
		
		while ((fib_1 + fib_2) < 4e6) {
			fib_0 = fib_1 + fib_2;	// calculating new value
			
//			System.out.print("Fibonacci number = " + fib_0);
			
			if ( (fib_0 % 2) == 0 )	sumEvenFib += fib_0; 
			
			// shifting Variables
			fib_2 = fib_1;
			fib_1 = fib_0;
			
//			System.out.println();
		};
		
		System.out.println();
		System.out.println("The sum of all even Values is: " + sumEvenFib);
		
	}

}
